let sos=[],resources=[],responders=[],applications=[],blockages=[],notifications=[],audit=[],tab='overview',map=null,markerLayer=null,lastSOSIds=new Set(),firstLoad=true,routeSelectedId='',routeSelectedResponderId='',routeCache={},overviewView={center:[15.8281,78.0373],zoom:13};const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const api=async(path,opt={})=>{const token=sessionStorage.getItem('rescuez_admin_token');const headers={...(opt.headers||{}),...(token?{'Authorization':'Bearer '+token}:{})};const r=await fetch(path,{...opt,headers}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};
function toast(msg,type='ok'){const t=$('toast');t.textContent=msg;t.className='toast '+type;clearTimeout(window.tt);window.tt=setTimeout(()=>t.className='',3200)}
async function load(initial=false){try{const [a,b]=await Promise.all([api('/api/sos'),api('/api/bootstrap')]);const incoming=a.sos||[];if(!initial&&!firstLoad){const fresh=incoming.filter(x=>!lastSOSIds.has(x.id));fresh.forEach(showEmergencyAlert)}sos=incoming;resources=b.resources||[];responders=b.responders||[];applications=b.responderApplications||[];blockages=b.roadBlockages||[];notifications=b.notifications||[];audit=b.audit||[];lastSOSIds=new Set(sos.map(x=>x.id));firstLoad=false;if(initial||!$('adminView').children.length)render();else refreshCurrent()}catch(e){toast(e.message,'error')}}
function refreshCurrent(){if(tab==='overview'){updateOverview();return}if(tab==='incidents'){filterIncidents();return}if(tab==='resources'){const g=$('resourceGrid');if(g)g.innerHTML=resourceCards();return}if(tab==='responders'){return}if(tab==='audit'){return}}
function syncRoutingData(){const sel=$('routeIncident'),rs=$('routeResponder');if(!sel)return;const active=sos.filter(x=>x.status!=='RESOLVED');const ids=new Set(active.map(x=>x.id));if(routeSelectedId&&!ids.has(routeSelectedId)){routeSelectedId='';routeSelectedResponderId='';}const sig=active.map(x=>x.id+':'+x.priority).join('|');if(sel.dataset.signature!==sig){const old=routeSelectedId;sel.dataset.signature=sig;sel.innerHTML='<option value="">Select incident…</option>'+active.map(x=>`<option value="${x.id}">${x.id} — ${esc(x.category)} — ${x.priority}</option>`).join('');sel.value=old||'';}else sel.value=routeSelectedId||'';if(rs){const incident=sos.find(x=>x.id===routeSelectedId);const candidates=responders.filter(r=>r.status==='AVAILABLE').map(r=>({...r,distance:haversine(r.lat,r.lng,incident?.lat,incident?.lng)})).sort((a,b)=>a.distance-b.distance);const oldR=routeSelectedResponderId;rs.innerHTML='<option value="">Select responder…</option>'+candidates.map(r=>`<option value="${r.id}">${esc(r.name)} — ${r.distance.toFixed(2)} km</option>`).join('');if(candidates.some(r=>r.id===oldR))rs.value=oldR;else if(candidates[0]&&routeSelectedId&&!oldR){routeSelectedResponderId=candidates[0].id;rs.value=candidates[0].id}else rs.value='';}}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('pageTitle').textContent={overview:'Command Center',incidents:'SOS Queue',resources:'Resource Readiness',responders:'Responder Network',routing:'Routing Intelligence',audit:'Audit Log'}[tab];({overview:renderOverview,incidents:renderIncidents,resources:renderResources,responders:renderResponders,routing:renderRouting,audit:renderAudit}[tab])();$('notifCount').textContent=notifications.length}
function overviewMarkup(){return `<div class="kpi-grid" id="kpis"></div><div class="command-grid"><section class="panel map-panel"><div class="panel-head"><div><div class="eyebrow">LIVE GEOSPATIAL VIEW</div><h2>Emergency Operations Map</h2></div><div class="legend"><i class="red"></i>Critical <i class="amber"></i>High <i class="cyan"></i>Other</div></div><div id="adminMap" class="bigmap"></div></section><section class="panel queue-panel"><div class="panel-head"><div><div class="eyebrow">LIVE PRIORITY QUEUE</div><h2>Incoming SOS</h2></div><span class="pill CRITICAL" id="queueCount">0</span></div><div id="overviewQueue" class="queue"></div></section></div><div class="quick-grid"><button onclick="tab='incidents';render()">🚨<b>Review SOS queue</b><span>Prioritize active emergencies</span></button><button onclick="tab='resources';render()">▣<b>Manage resources</b><span>Add and update supplies</span></button><button onclick="tab='responders';render()">♢<b>Join / manage responders</b><span>Verify response teams</span></button></div>`}
function renderOverview(){if(map){try{overviewView={center:[map.getCenter().lat,map.getCenter().lng],zoom:map.getZoom()};map.remove()}catch{}map=null;markerLayer=null}$('adminView').innerHTML=overviewMarkup();setTimeout(()=>{initMap();if(map){map.setView(overviewView.center,overviewView.zoom,{animate:false});map.invalidateSize()}updateOverview()},60)}
function updateOverview(){const active=sos.filter(x=>!['RESOLVED','CANCELLED'].includes(x.status)),crit=active.filter(x=>x.priority==='CRITICAL'),people=active.reduce((a,x)=>a+(+x.people||0),0);const k=$('kpis');if(k)k.innerHTML=`<div class="metric"><span>ACTIVE SOS</span><b>${active.length}</b><small>Live requests</small></div><div class="metric critical-m"><span>CRITICAL</span><b>${crit.length}</b><small>Immediate action</small></div><div class="metric"><span>PEOPLE AFFECTED</span><b>${people}</b><small>Active incidents</small></div><div class="metric"><span>RESPONDERS AVAILABLE</span><b>${responders.filter(x=>x.status==='AVAILABLE').length}</b><small>Nearby teams ready</small></div>`;const q=$('overviewQueue');if(q)q.innerHTML=active.sort((a,b)=>b.priorityScore-a.priorityScore).slice(0,15).map(card).join('')||empty('No active SOS','Waiting for incoming emergency requests.');if($('queueCount'))$('queueCount').textContent=active.length;updateMapMarkers()}
function card(x){return `<div class="incident-card ${x.priority==='CRITICAL'?'critical':''}"><div class="incident-top"><span class="pill ${x.priority}">${x.priority}</span><span class="muted">${timeAgo(x.createdAt)}</span></div><h3>${esc(x.category)} · ${esc(x.id)}</h3><p>${esc(x.name)} · ${x.people} people · ${esc(x.status)}</p><div class="score"><b>${x.priorityScore}/100</b><span>${esc(x.needs||'Assistance required')}</span></div><div class="actions"><button class="ghost" onclick="showDetail('${x.id}')">View details</button><button class="primary" onclick="dispatch('${x.id}')">🚑 Dispatch</button></div></div>`}
function initMap(){const el=$('adminMap');if(!el)return;if(map){map.invalidateSize();return}map=L.map(el,{zoomControl:true,scrollWheelZoom:true,doubleClickZoom:true}).setView([15.8281,78.0373],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),200);updateMapMarkers()}
function updateMapMarkers(){if(!map||!markerLayer)return;markerLayer.clearLayers();responders.filter(r=>r.status==='EN_ROUTE'||r.status==='BUSY'||(r.assignments||[]).length).forEach(r=>{L.marker([r.lat,r.lng],{title:'Live responder location'}).addTo(markerLayer).bindPopup('🚑 '+esc(r.name)+' · live/last GPS');});sos.filter(x=>x.status!=='RESOLVED').forEach(x=>{const c=x.priority==='CRITICAL'?'#ff416c':x.priority==='HIGH'?'#ffb347':'#30d9ff';L.circleMarker([x.lat,x.lng],{radius:x.priority==='CRITICAL'?11:8,color:c,fillColor:c,fillOpacity:.85,weight:2}).addTo(markerLayer).bindPopup(`<b>${esc(x.id)}</b><br>${esc(x.category)}<br>${esc(x.name)}<br>Priority ${x.priorityScore}/100`)});blockages.forEach(b=>L.circleMarker([b.lat,b.lng],{radius:7,color:'#fff',fillColor:'#111',fillOpacity:.9}).addTo(markerLayer).bindTooltip('Road blockage: '+esc(b.road)))}
function renderIncidents(){$('adminView').innerHTML=`<div class="toolbar"><input id="search" placeholder="Search ID, victim, emergency…" oninput="filterIncidents()"><select id="filter" onchange="filterIncidents()"><option>ALL</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><button class="primary" onclick="showBlockageForm()">+ Road blockage</button></div><div class="panel tablewrap"><table><thead><tr><th>PRIORITY</th><th>INCIDENT</th><th>VICTIM</th><th>PEOPLE</th><th>LOCATION</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody id="incidentTable"></tbody></table></div>`;filterIncidents()}
function filterIncidents(){const q=($('search')?.value||'').toLowerCase(),f=$('filter')?.value||'ALL';const list=sos.filter(x=>(f==='ALL'||x.priority===f)&&`${x.id} ${x.name} ${x.category}`.toLowerCase().includes(q)).sort((a,b)=>b.priorityScore-a.priorityScore);$('incidentTable').innerHTML=list.map(x=>`<tr><td><span class="pill ${x.priority}">${x.priority}</span><small>${x.priorityScore}/100</small></td><td><b>${esc(x.id)}</b><small>${esc(x.category)}</small></td><td>${esc(x.name)}<small>${esc(x.phone||'No phone')}</small></td><td>${x.people}</td><td>${(+x.lat).toFixed(4)}, ${(+x.lng).toFixed(4)}</td><td>${esc(x.status)}</td><td><button class="ghost" onclick="showDetail('${x.id}')">Open</button></td></tr>`).join('')||`<tr><td colspan="7">No incidents found.</td></tr>`}
function renderResources(){$('adminView').innerHTML=`<div class="panel resource-add"><div class="panel-head"><div><div class="eyebrow">RESOURCE INVENTORY</div><h2>Add resource</h2></div><span class="secure">Inventory updates are persistent</span></div><form id="resourceForm" class="formgrid"><div class="field"><label>Resource name *</label><input id="resourceName" required placeholder="Drinking Water"></div><div class="field"><label>Quantity *</label><input id="resourceQty" type="number" min="1" required placeholder="500"></div><div class="field"><label>Unit</label><input id="resourceUnit" placeholder="units"></div><div class="field"><label>Supplier / location</label><input id="resourceSupplier" placeholder="Local Relief Hub"></div><div class="field full"><button class="primary" type="submit">+ Add resource</button></div></form></div><div class="resource-grid" id="resourceGrid">${resourceCards()}</div>`;$('resourceForm').onsubmit=addResource}
function resourceCards(){return resources.map(r=>`<div class="panel resource-card"><div class="resource-icon">▣</div><div class="eyebrow">${esc(r.supplier)}</div><h2>${esc(r.type)}</h2><b class="resource-num">${Number(r.qty).toLocaleString()}</b><span>${esc(r.unit)} available</span><div class="progress"><i style="width:${r.capacity}%"></i></div><small>${r.capacity}% operational capacity</small></div>`).join('')||empty('No resources','Add the first resource to the network.')}
async function addResource(e){e.preventDefault();try{await api('/api/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:$('resourceName').value,qty:+$('resourceQty').value,unit:$('resourceUnit').value,supplier:$('resourceSupplier').value})});toast('Resource added successfully.');await load(true)}catch(err){toast(err.message,'error')}}
function renderResponders(){$('adminView').innerHTML=`<div class="panel responder-join"><div class="panel-head"><div><div class="eyebrow">RESPONDER NETWORK</div><h2>Join RescuEZ</h2><p class="muted">Volunteers and response teams can submit basic details, organization location and identity proof for admin verification.</p></div></div></div><div class="panel"><div class="panel-head"><h2>Pending applications</h2><span class="pill HIGH">${applications.filter(x=>x.status==='PENDING').length} pending</span></div><div class="application-list">${applications.filter(x=>x.status==='PENDING').map(applicationCard).join('')||empty('No pending applications','New volunteer or responder applications will appear here.')}</div></div><div class="responder-grid">${responders.map(r=>`<div class="panel responder"><div class="avatar">${r.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2>${esc(r.name)}</h2><span class="status-tag ${r.status}">${r.status}</span><p class="muted">${esc(r.organization||'Independent')}<br>${(r.skills||[]).map(esc).join(' • ')}</p><small>📍 ${Number(r.lat).toFixed(4)}, ${Number(r.lng).toFixed(4)}</small><div class="actions" style="margin-top:12px"><button class="danger" onclick="removeResponder('${r.id}')">🗑 Remove responder</button></div></div></div>`).join('')||empty('No responders','Approved responders will appear here.')}</div>`}
function applicationCard(a){return `<div class="application"><div><b>${esc(a.name)}</b><small>${esc(a.organization)} · ${esc(a.phone)}</small><small>📍 ${esc(a.location)}</small><small>Identity: ${esc(a.identityType)}</small></div><div class="actions"><button class="ghost" onclick="viewIdentity('${a.id}')">View proof</button><button class="primary" onclick="approveApp('${a.id}')">Approve</button><button class="danger" onclick="rejectApp('${a.id}')">Reject</button></div></div>`}
function viewIdentity(id){const a=applications.find(x=>x.id===id);if(!a)return;const isPdf=String(a.identityProof).startsWith('data:application/pdf');$('modalRoot').innerHTML=`<div class="modal"><div class="modalbox large"><div class="modal-head"><h2>Identity verification · ${esc(a.name)}</h2><button class="ghost" onclick="closeModal()">✕</button></div>${isPdf?`<iframe src="${a.identityProof}" style="width:100%;height:600px;border:0"></iframe>`:`<img src="${a.identityProof}" style="max-width:100%;max-height:600px;display:block;margin:auto;border-radius:12px">`}</div></div>`}
async function removeResponder(id){
 const r=responders.find(x=>x.id===id);if(!r)return;
 if(!confirm(`Remove ${r.name} from the responder network?`))return;
 try{await api('/api/responders/'+encodeURIComponent(id),{method:'DELETE'});toast('Responder removed from the network.');await load(true)}
 catch(e){toast(e.message,'error')}
}
async function approveApp(id){try{await api('/api/responder-applications/'+id+'/approve',{method:'POST'});closeModal();toast('Responder approved and added to nearby assignment network.');await load(true)}catch(e){toast(e.message,'error')}}async function rejectApp(id){try{await api('/api/responder-applications/'+id+'/reject',{method:'POST'});toast('Application rejected.');await load(true)}catch(e){toast(e.message,'error')}}
function renderRouting(){const keep=routeSelectedId,keepR=routeSelectedResponderId; $('adminView').innerHTML=`<div class="routing-hero panel"><div><div class="eyebrow">OPTIMIZATION ENGINE</div><h2>Shortest is not always safest.</h2><p>Select an incident and a nearby available responder. A* or Dijkstra calculates the route without rebuilding this section.</p></div><select id="routeIncident"><option value="">Select incident…</option>${sos.filter(x=>x.status!=='RESOLVED').map(x=>`<option value="${x.id}">${x.id} — ${esc(x.category)} — ${x.priority}</option>`).join('')}</select><select id="routeResponder"><option value="">Select responder…</option></select><div class="algorithm-buttons"><button class="primary" onclick="calcRoute('A*')">Run A*</button><button class="ghost" onclick="calcRoute('Dijkstra')">Run Dijkstra</button></div></div><div id="routeResult" class="panel route-result">Choose an incident, responder and algorithm.</div>`;const sel=$('routeIncident'),rs=$('routeResponder');if(sel){sel.dataset.signature=sos.filter(x=>x.status!=='RESOLVED').map(x=>x.id+':'+x.priority).join('|');sel.value=keep||'';routeSelectedId=sel.value||keep||'';sel.addEventListener('change',()=>{routeSelectedId=sel.value;routeSelectedResponderId='';syncRoutingData()});}if(rs){routeSelectedResponderId=keepR||'';rs.addEventListener('change',()=>routeSelectedResponderId=rs.value);}syncRoutingData();rehydrateRoute();}
async function calcRoute(algorithm){const sel=$('routeIncident'),rs=$('routeResponder'),id=sel?.value||routeSelectedId,rid=rs?.value||routeSelectedResponderId;routeSelectedId=id;routeSelectedResponderId=rid;if(!id)return toast('Select an incident first.','error');if(!rid)return toast('Select an available responder team.','error');try{const d=await api('/api/sos/'+id+'/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({algorithm,responderId:rid})});routeCache[id]={...d.route,responderId:rid};renderRouteResult(d.route,id);toast(`${algorithm} route calculated.`)}catch(e){toast(e.message,'error')}}
function renderRouteResult(route,id){const r=responders.find(x=>x.id===route.responderId)||responders.find(x=>x.id===route.responderId);$('routeResult').innerHTML=`<div class="route-result-grid"><div><span>ALGORITHM</span><b>${route.algorithm}</b></div><div><span>DISTANCE</span><b>${route.distanceKm} km</b></div><div><span>ETA</span><b>${route.etaMin} min</b></div><div><span>SAFETY</span><b>${route.safety}%</b></div><div><span>NODES EXPLORED</span><b>${route.nodesExplored}</b></div></div><div id="routeMap" style="height:390px;margin-top:18px;border-radius:14px;overflow:hidden"></div><div class="route-line"><span>${esc(r?.name||'Responder')}</span><b>→ ${route.algorithm} optimized road route →</b><span>Incident ${id}</span></div>`;drawRouteMap(route);}
async function drawRouteMap(route){const el=$('routeMap');if(!el)return;const s=responders.find(x=>x.id===route.responderId),i=sos.find(x=>x.id===route.incidentId);if(!s||!i)return;const rm=L.map(el,{zoomControl:true,scrollWheelZoom:true}).setView([i.lat,i.lng],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(rm);L.marker([s.lat,s.lng]).addTo(rm).bindPopup('Responder: '+esc(s.name)).openPopup();L.marker([i.lat,i.lng]).addTo(rm).bindPopup('Incident: '+esc(i.id));try{const q=await fetch(`https://router.project-osrm.org/route/v1/driving/${s.lng},${s.lat};${i.lng},${i.lat}?overview=full&geometries=geojson`).then(x=>x.json());if(q.routes?.[0]){const line=L.geoJSON(q.routes[0].geometry,{style:{weight:6}}).addTo(rm);rm.fitBounds(line.getBounds(),{padding:[30,30]});return}}catch{}L.polyline([[s.lat,s.lng],[i.lat,i.lng]],{weight:5,dashArray:'8 8'}).addTo(rm);rm.fitBounds([[s.lat,s.lng],[i.lat,i.lng]],{padding:[30,30]})}
function rehydrateRoute(){const cached=routeCache[routeSelectedId];if(cached&&routeSelectedResponderId===cached.responderId)renderRouteResult(cached,routeSelectedId)}
function renderAudit(){$('adminView').innerHTML=`<section class="panel"><div class="panel-head"><h2>Activity trail</h2><span class="muted">Latest ${audit.length} events</span></div><div class="audit-list">${audit.map(a=>`<div><span class="audit-dot"></span><div><b>${esc(a.action)}</b><small>${esc(a.entity)} • ${new Date(a.createdAt).toLocaleString()}</small><code>${esc(JSON.stringify(a.details))}</code></div></div>`).join('')||empty('No activity yet','Actions appear here automatically.')}</div></section>`}
async function showDetail(id){const x=sos.find(a=>a.id===id);if(!x)return;const nearby=responders.filter(r=>r.status==='AVAILABLE').map(r=>({...r,distance:haversine(r.lat,r.lng,x.lat,x.lng)})).sort((a,b)=>a.distance-b.distance);const need=Math.max(1,Math.ceil((+x.people||1)/6)+(x.priority==='CRITICAL'&&((+x.people||1)>=8||x.trapped)?1:0));const assigned=(x.assignedResponders||[]).map(id=>responders.find(r=>r.id===id)?.name||id);$('modalRoot').innerHTML=`<div class="modal"><div class="modalbox large"><div class="modal-head"><div><span class="pill ${x.priority}">${x.priority} · ${x.priorityScore}/100</span><h2>${esc(x.id)}</h2></div><button class="ghost" onclick="closeModal()">✕</button></div><div class="detail-grid"><div><small>VICTIM</small><b>${esc(x.name)}</b></div><div><small>PHONE</small><b>${esc(x.phone||'Not provided')}</b></div><div><small>EMERGENCY</small><b>${esc(x.category)}</b></div><div><small>PEOPLE AFFECTED</small><b>${x.people}</b></div><div><small>LATITUDE</small><b>${x.lat}</b></div><div><small>LONGITUDE</small><b>${x.lng}</b></div><div><small>STATUS</small><b>${esc(x.status)}</b></div><div><small>ASSIGNED TEAMS</small><b>${assigned.length||0}</b></div></div><div class="explain"><b>Nearby assignment engine</b><span>Required teams: ${need}. Available nearby: ${nearby.length}. The closest free teams are preferred; already busy teams are excluded. Large incidents can receive multiple teams.</span></div><div class="nearby-list">${nearby.slice(0,6).map(r=>`<label class="nearby-item"><input type="checkbox" name="nearResponder" value="${r.id}" ${assigned.includes(r.name)?'checked':''}><span><b>${esc(r.name)}</b><small>${esc(r.organization||'')} · ${r.distance.toFixed(2)} km away · ${esc(r.skills.join(' • '))}</small></span></label>`).join('')||empty('No free nearby responders','New approved responders will appear here when available.')}</div><div class="detail-description"><b>Needs</b><p>${esc(x.needs||'Not specified')}</p><b>Description</b><p>${esc(x.description||'No description provided.')}</p></div><div class="modal-actions"><button class="ghost" onclick="window.open('https://www.google.com/maps?q=${x.lat},${x.lng}','_blank')">⌖ Open exact location</button><button class="ghost" onclick="routeSelectedId='${x.id}';closeModal();tab='routing';render()">⌁ Routing intelligence</button><button class="primary" onclick="dispatch('${x.id}')">🚑 Assign selected nearby teams</button><button class="danger" onclick="resolveIncident('${x.id}')">Resolve</button></div></div></div>`}
function closeModal(){$('modalRoot').innerHTML=''}
async function dispatch(id){const selected=[...document.querySelectorAll('input[name="nearResponder"]:checked')].map(x=>x.value);try{const r=await api('/api/sos/'+id+'/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({responderIds:selected})});toast(`${r.responders.length} nearby responder${r.responders.length>1?'s':''} dispatched.`);closeModal();await load(true)}catch(e){toast(e.message,'error')}}
async function resolveIncident(id){try{await api('/api/sos/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'RESOLVED'})});closeModal();toast('Incident resolved. Responders released.');await load(true)}catch(e){toast(e.message,'error')}}
function showBlockageForm(){
  $('modalRoot').innerHTML=`<div class="modal"><div class="modalbox large blockage-modal">
    <div class="modal-head"><div><div class="eyebrow">ROAD SAFETY</div><h2>Manage road blockages</h2></div><button class="ghost" onclick="closeModal()">✕</button></div>
    <div class="blockage-tabs">
      <button class="primary" id="addBlockMode" type="button">⌖ Select blockage on map</button>
      <button class="ghost" id="removeBlockMode" type="button">🗑 Remove blockage</button>
    </div>
    <div class="formgrid">
      <div class="field full"><label>Road name / description</label><input id="blockRoad" placeholder="Main Road, bridge, debris..."></div>
      <div class="field"><label>Latitude *</label><input id="blockLat" required readonly placeholder="Select on map"></div>
      <div class="field"><label>Longitude *</label><input id="blockLng" required readonly placeholder="Select on map"></div>
    </div>
    <div id="blockMap" class="blockage-map"></div>
    <div id="blockMapHint" class="muted blockage-hint">Select blockage on map, then click the exact road location.</div>
    <div class="modal-actions"><button class="primary" id="saveBlockage" type="button">Add blockage</button></div>
  </div></div>`;

  let mode='add', picked=null, pickedMarker=null;
  const center=blockages.length ? [blockages[0].lat,blockages[0].lng] : [15.8281,78.0373];
  const bm=L.map('blockMap',{zoomControl:true}).setView(center,13);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(bm);
  const layer=L.layerGroup().addTo(bm);

  function setMode(next){
    mode=next; layer.clearLayers(); picked=null; if(pickedMarker){pickedMarker.remove();pickedMarker=null}
    $('addBlockMode').className=next==='add'?'primary':'ghost';
    $('removeBlockMode').className=next==='remove'?'primary':'ghost';
    $('saveBlockage').style.display=next==='add'?'inline-flex':'none';
    $('blockMapHint').textContent=next==='add'
      ? 'Click the exact road location to select the new blockage.'
      : (blockages.length ? 'Click one blockage marker to remove only that blockage.' : 'No road blockages to remove.');
    if(next==='remove'){
      blockages.forEach(b=>{
        L.circleMarker([b.lat,b.lng],{radius:10,color:'#ff6b6b',fillColor:'#ff416c',fillOpacity:.9,weight:2})
          .addTo(layer)
          .bindTooltip(`Remove: ${esc(b.road||b.id)}`)
          .on('click',async()=>{
            if(!confirm(`Remove blockage "${b.road||b.id}" only?`)) return;
            try{
              await api('/api/road-blockages/'+encodeURIComponent(b.id),{method:'DELETE'});
              toast('Selected blockage removed.');
              closeModal();
              await load(true);
              showBlockageForm();
            }catch(e){toast(e.message,'error')}
          });
      });
    }
  }

  bm.on('click',e=>{
    if(mode!=='add') return;
    picked=[e.latlng.lat,e.latlng.lng];
    $('blockLat').value=e.latlng.lat.toFixed(6);
    $('blockLng').value=e.latlng.lng.toFixed(6);
    if(pickedMarker) pickedMarker.setLatLng(picked);
    else pickedMarker=L.marker(picked).addTo(bm);
    $('blockMapHint').textContent='✓ Location selected. Add a road name and save the blockage.';
  });
  $('addBlockMode').onclick=()=>setMode('add');
  $('removeBlockMode').onclick=()=>setMode('remove');
  $('saveBlockage').onclick=async()=>{
    if(!picked)return toast('Select the blockage location on the map first.','error');
    try{
      await api('/api/road-blockages',{method:'POST',headers:{'Content-Type':'application/json'},
        body:JSON.stringify({road:$('blockRoad').value,lat:+$('blockLat').value,lng:+$('blockLng').value})});
      closeModal();toast('Road blockage added.');await load(true);
    }catch(e){toast(e.message,'error')}
  };
  setTimeout(()=>bm.invalidateSize(),100);
}
function showNotifications(){$('modalRoot').innerHTML=`<div class="modal"><div class="modalbox large"><div class="modal-head"><div><div class="eyebrow">COMMAND NOTIFICATIONS</div><h2>All notifications</h2></div><button class="ghost" onclick="closeModal()">✕</button></div><div class="notification-list">${notifications.map(n=>`<div class="notification ${n.type==='SOS'?'urgent':''}"><span>${n.type==='SOS'?'🚨':n.type==='ASSIGNMENT'?'🚑':n.type==='APPLICATION'?'♢':n.type==='MESSAGE'?'💬':'●'}</span><div><b>${esc(n.title)}</b><p>${esc(n.message)}</p><small>${new Date(n.createdAt).toLocaleString()}</small></div></div>`).join('')||empty('No notifications','You are all caught up.')}</div></div></div>`}
function adminBuzzer(duration=3000){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=window._rzAdminAudio||new C();window._rzAdminAudio=ctx;if(ctx.state==='suspended')ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='square';osc.frequency.value=820;gain.gain.setValueAtTime(.0001,now);for(let t=0;t<duration/1000;t+=.4){gain.gain.setValueAtTime(.0001,now+t);gain.gain.exponentialRampToValueAtTime(.16,now+t+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+t+.16)}osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+duration/1000+.05)}catch{}}function showEmergencyAlert(x){try{if(navigator.vibrate)navigator.vibrate([250,120,250,120,500])}catch{}adminBuzzer(3000);$('modalRoot').innerHTML=`<div class="emergency-overlay"><div class="emergency-alert"><div class="alert-pulse">🚨</div><div class="eyebrow">INCOMING EMERGENCY</div><h1>${esc(x.priority)} SOS</h1><h2>${esc(x.category)} · ${esc(x.id)}</h2><p><b>${esc(x.name)}</b> needs assistance at <b>${Number(x.lat).toFixed(5)}, ${Number(x.lng).toFixed(5)}</b>.</p><div class="alert-actions"><button class="primary" onclick="closeModal();showDetail('${x.id}')">OPEN INCIDENT</button><button class="ghost" onclick="closeModal()">ACKNOWLEDGE</button></div></div></div>`}
function empty(title,text){return `<div class="empty"><b>${title}</b><span>${text}</span></div>`}function timeAgo(s){const m=Math.max(0,Math.round((Date.now()-new Date(s))/60000));return m<1?'just now':m+'m ago'}function haversine(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('notifBtn').onclick=showNotifications;setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString()},1000);load(true);setInterval(()=>load(false),2500);

async function removeBlockage(id){await api('/api/road-blockages/'+id,{method:'DELETE'});toast('Selected blockage removed.');await load(true)}

async 
