const http=require('http'),fs=require('fs'),path=require('path'),url=require('url'),crypto=require('crypto');
// Load .env without requiring an external dependency
const ENV_FILE=path.join(__dirname,'.env');
if(fs.existsSync(ENV_FILE)){for(const line of fs.readFileSync(ENV_FILE,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);if(m&&!m[1].startsWith('#')&&process.env[m[1]]===undefined){let v=m[2];if((v.startsWith('\"')&&v.endsWith('\"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[m[1]]=v}}}
const PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'0.0.0.0',ROOT=__dirname,DB=path.join(ROOT,process.env.DATA_FILE||'data.json');
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'CHANGE_THIS_ADMIN_PASSWORD';
const SESSION_TTL_MS=Number(process.env.SESSION_TTL_MS||8*60*60*1000);
const ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'';
const ADMIN_PATH=(process.env.ADMIN_PATH||'/owner-command-center').replace(/\/+$/,'')||'/owner-command-center';
const ADMIN_ALLOWED_IP=(process.env.ADMIN_ALLOWED_IP||'').trim();
function clientIP(req){return String(req.socket.remoteAddress||'').replace(/^::ffff:/,'')}
function ownerAllowed(req){return !ADMIN_ALLOWED_IP||clientIP(req)===ADMIN_ALLOWED_IP}

const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
const sessions=new Map(), loginAttempts=new Map();
function newSession(role,id){const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{role,id,expires:Date.now()+SESSION_TTL_MS});return token}
function getSession(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const x=sessions.get(token);if(!x||x.expires<Date.now()){if(token)sessions.delete(token);return null}return x}
function requireAdmin(req,res){const x=getSession(req);if(!x||x.role!=='admin'){json(res,401,{error:'Admin authentication required'});return null}return x}
function requireResponder(req,res,id){const x=getSession(req);if(!x||x.role!=='responder'||x.id!==id){json(res,401,{error:'Responder authentication required'});return null}return x}
function rateKey(req,key){return req.socket.remoteAddress+'|'+key}
function loginAllowed(req,key){const k=rateKey(req,key),x=loginAttempts.get(k)||{n:0,t:Date.now()};if(Date.now()-x.t>10*60*1000){loginAttempts.delete(k);return true}return x.n<10}
function failedLogin(req,key){const k=rateKey(req,key),x=loginAttempts.get(k)||{n:0,t:Date.now()};x.n++;loginAttempts.set(k,x)}

const seed={sos:[],responders:[{id:'RESP-01',name:'Rapid Response Team A',organization:'RescuEZ Medical Response',status:'AVAILABLE',lat:15.832,lng:78.041,skills:['Medical','Rescue'],phone:'+91 90000 10001',verified:true},{id:'RESP-02',name:'Medical Unit B',organization:'Kurnool Relief Network',status:'AVAILABLE',lat:15.818,lng:78.03,skills:['Medical'],phone:'+91 90000 10002',verified:true}],responderApplications:[],resources:[{id:'RES-01',type:'Drinking Water',qty:1240,unit:'units',supplier:'Relief Hub A',lat:15.84,lng:78.02,capacity:82},{id:'RES-02',type:'First Aid Kits',qty:184,unit:'kits',supplier:'Relief Hub B',lat:15.81,lng:78.05,capacity:55},{id:'RES-03',type:'Food Packets',qty:760,unit:'packets',supplier:'Relief Hub C',lat:15.80,lng:78.01,capacity:38},{id:'RES-04',type:'Blankets',qty:420,unit:'units',supplier:'Relief Hub A',lat:15.84,lng:78.02,capacity:82}],roadBlockages:[],notifications:[],audit:[]};
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed,null,2));
function read(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return JSON.parse(JSON.stringify(seed))}}
function write(d){const tmp=DB+'.tmp';fs.writeFileSync(tmp,JSON.stringify(d,null,2),{mode:0o600});fs.renameSync(tmp,DB)}
function json(res,status,data){const origin=reqOrigin(res.req);const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin','Permissions-Policy':'geolocation=(self)','Access-Control-Allow-Headers':'Content-Type, Authorization'};if(origin)h['Access-Control-Allow-Origin']=origin;res.writeHead(status,h);res.end(JSON.stringify(data))}
function reqOrigin(req){if(!ALLOWED_ORIGIN)return '';const o=req?.headers?.origin||'';return o===ALLOWED_ORIGIN?o:''}
function body(req){return new Promise((resolve,reject)=>{let b='';let size=0;req.on('data',c=>{size+=c.length;if(size>1024*1024){reject(Error('Request too large'));req.destroy()}else b+=c});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function audit(d,action,entity,details={}){d.audit.unshift({id:crypto.randomUUID(),action,entity,details,createdAt:new Date().toISOString()});d.audit=d.audit.slice(0,500)}
function notify(d,type,title,message,sosId=null){d.notifications.unshift({id:crypto.randomUUID(),type,title,message,sosId,createdAt:new Date().toISOString(),read:false});d.notifications=d.notifications.slice(0,300)}
function priority(b){let score=(+b.severityScore||50)+Math.min(20,(+b.people||1)*3)+(b.medical?18:0)+(b.trapped?22:0)+(b.children?10:0)+(b.noWater?8:0);score=Math.min(100,Math.round(score));return{score,level:score>=75?'CRITICAL':score>=50?'HIGH':score>=25?'MEDIUM':'LOW'}}
function haversine(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function responderNeed(s){return Math.max(1,Math.ceil((+s.people||1)/6)+(s.priority==='CRITICAL'&&((+s.people||1)>=8||s.category==='Rescue'||s.trapped)?1:0))}
function eligibleResponders(d,s){return d.responders.filter(r=>r.status==='AVAILABLE'||r.status==='EN_ROUTE').map(r=>({...r,distanceKm:haversine(r.lat,r.lng,s.lat,s.lng)})).filter(r=>r.status==='AVAILABLE').sort((a,b)=>a.distanceKm-b.distanceKm)}
const server=http.createServer(async(req,res)=>{res.req=req;const u=url.parse(req.url,true);let p=u.pathname;
try{
if(req.method==='OPTIONS'){const origin=reqOrigin(req);const h={'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'};if(origin)h['Access-Control-Allow-Origin']=origin;res.writeHead(204,h);return res.end()}
let d=read();
const adminProtected=(p==='/api/resources'||p==='/api/responder-applications'||p==='/api/road-blockages'||p==='/api/bootstrap'||(/^\/api\/sos\/[^/]+\/(assign|resolve|route)$/.test(p))||(/^\/api\/sos\/[^/]+$/.test(p)&&req.method==='PATCH'));
if(adminProtected && req.method!=='GET' && !requireAdmin(req,res))return;
if(p==='/api/health')return json(res,200,{status:'operational',database:'local-json',time:new Date().toISOString()});
if(p==='/api/admin/login'&&req.method==='POST'){if(!ownerAllowed(req))return json(res,403,{error:'Admin login is allowed only from the configured owner device/IP'});if(!loginAllowed(req,'admin'))return json(res,429,{error:'Too many login attempts. Try again later.'});const b=await body(req);if(String(ADMIN_PASSWORD).startsWith('CHANGE_THIS'))return json(res,503,{error:'Server admin password is not configured. Set ADMIN_PASSWORD before deployment.'});if(crypto.timingSafeEqual(Buffer.from(hash(b.password||'')),Buffer.from(hash(ADMIN_PASSWORD)))){loginAttempts.delete(rateKey(req,'admin'));return json(res,200,{success:true,token:newSession('admin','admin')})}failedLogin(req,'admin');return json(res,401,{error:'Invalid admin password'})}
if(p==='/api/bootstrap'&&req.method==='GET'){if(!requireAdmin(req,res))return;return json(res,200,{resources:d.resources,responders:d.responders,responderApplications:d.responderApplications,roadBlockages:d.roadBlockages,notifications:d.notifications.slice(0,100),audit:d.audit.slice(0,100)});}
if(p==='/api/sos'&&req.method==='GET')return json(res,200,{sos:d.sos});
if(p==='/api/sos'&&req.method==='POST'){
 const b=await body(req);if(!b.name||!b.category||!Number.isFinite(+b.lat)||!Number.isFinite(+b.lng))return json(res,400,{error:'Name, emergency type and valid location are required.'});
 const pr=priority(b),item={id:'RZ-'+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),status:'NEW',priorityScore:pr.score,priority:pr.level,assignedResponders:[],statusHistory:[{status:'NEW',at:new Date().toISOString(),note:'SOS received by RescuEZ command center'}],...b,lat:+b.lat,lng:+b.lng,people:+b.people||1};
 d.sos.unshift(item);notify(d,'SOS','New '+pr.level+' SOS',`${item.name} reported ${item.category}`,item.id);audit(d,'SOS_CREATED',item.id,{priority:item.priority,category:item.category,location:{lat:item.lat,lng:item.lng}});write(d);return json(res,201,{success:true,sos:item})}
if(p.startsWith('/api/sos/')&&req.method==='GET'&&p.split('/').length===4){const id=p.split('/')[3],x=d.sos.find(x=>x.id===id);if(!x)return json(res,404,{error:'SOS not found'});return json(res,200,{sos:x})}

if(p.startsWith('/api/sos/')&&p.endsWith('/assign')&&req.method==='POST'){
 const id=p.split('/')[3],b=await body(req),i=d.sos.findIndex(x=>x.id===id);if(i<0)return json(res,404,{error:'SOS not found'});const s=d.sos[i];const requested=Array.isArray(b.responderIds)?b.responderIds:[];let pool=eligibleResponders(d,s);let chosen=requested.length?pool.filter(r=>requested.includes(r.id)):pool.slice(0,responderNeed(s));if(!chosen.length)return json(res,409,{error:'No nearby available responder is currently free.'});
 chosen.forEach(r=>{const rr=d.responders.find(x=>x.id===r.id);if(rr)rr.status='EN_ROUTE'});d.sos[i].assignedResponders=[...new Set([...(s.assignedResponders||[]),...chosen.map(x=>x.id)])];d.sos[i].status='EN_ROUTE';d.sos[i].statusHistory=d.sos[i].statusHistory||[];d.sos[i].statusHistory.push({status:'EN_ROUTE',at:new Date().toISOString(),note:'Responder team dispatched'});audit(d,'RESPONDERS_ASSIGNED',id,{responders:chosen.map(x=>({id:x.id,distanceKm:x.distanceKm}))});notify(d,'ASSIGNMENT','Responder team dispatched',`${chosen.length} responder${chosen.length>1?'s':''} assigned to ${id}`,id);write(d);return json(res,200,{success:true,sos:d.sos[i],responders:chosen})}
if(p.startsWith('/api/sos/')&&req.method==='PATCH'){
 const id=p.split('/').pop(),b=await body(req),i=d.sos.findIndex(x=>x.id===id);if(i<0)return json(res,404,{error:'SOS not found'});d.sos[i]={...d.sos[i],...b,updatedAt:new Date().toISOString()};d.sos[i].statusHistory=d.sos[i].statusHistory||[];if(b.status&&b.status!==d.sos[i].statusHistory[d.sos[i].statusHistory.length-1]?.status)d.sos[i].statusHistory.push({status:b.status,at:new Date().toISOString(),note:b.note||`Status changed to ${b.status}`});if(b.status==='RESOLVED'){(d.sos[i].assignedResponders||[]).forEach(id=>{const r=d.responders.find(x=>x.id===id);if(r)r.status='AVAILABLE'});notify(d,'RESOLVED','Incident resolved',`${id} has been resolved`,id)}audit(d,'SOS_UPDATED',id,b);write(d);return json(res,200,{success:true,sos:d.sos[i]})}
if(p==='/api/notifications/read'&&req.method==='POST')return json(res,405,{error:'Notifications are view-only from this button.'});
if(p==='/api/road-blockages'&&req.method==='POST'){const b=await body(req);if(!Number.isFinite(+b.lat)||!Number.isFinite(+b.lng))return json(res,400,{error:'Valid location required'});const x={id:'RB-'+Date.now().toString().slice(-6),road:b.road||'Emergency Road',severity:b.severity||'HIGH',lat:+b.lat,lng:+b.lng,createdAt:new Date().toISOString()};d.roadBlockages.push(x);audit(d,'ROAD_BLOCKAGE_ADDED',x.id,x);write(d);return json(res,201,{success:true,blockage:x})}
if(p.startsWith('/api/sos/')&&p.endsWith('/resolve')&&req.method==='POST'){
 const id=p.split('/')[3],b=await body(req),s=d.sos.find(x=>x.id===id);
 if(!s)return json(res,404,{error:'SOS not found'});
 const responderId=b.responderId;
 if(responderId && !(s.assignedResponders||[]).includes(responderId))return json(res,403,{error:'Only an assigned responder can resolve this incident'});
 if(s.status==='RESOLVED')return json(res,200,{success:true,sos:s,message:'Incident already resolved'});
 s.status='RESOLVED';s.resolvedAt=new Date().toISOString();s.resolvedBy=responderId||null;
 s.statusHistory=s.statusHistory||[];s.statusHistory.push({status:'RESOLVED',at:s.resolvedAt,note:'Marked resolved by assigned responder'});
 (s.assignedResponders||[]).forEach(rid=>{const r=d.responders.find(x=>x.id===rid);if(r){r.status='AVAILABLE';r.assignments=(r.assignments||[]).filter(x=>x!==id)}});
 notify(d,'RESOLVED','Incident resolved',`${s.category} incident ${s.id} was marked RESOLVED by responder`,s.id,responderId||null);
 audit(d,'INCIDENT_RESOLVED',s.id,{responderId:responderId||null});
 write(d);return json(res,200,{success:true,sos:s,message:'Incident marked as resolved'});
}
if(p==='/api/responders/location'&&req.method==='POST'){const b=await body(req);if(!requireResponder(req,res,b.responderId))return;const r=d.responders.find(x=>x.id===b.responderId);if(!r)return json(res,404,{error:'Responder not found'});if(!Number.isFinite(+b.lat)||!Number.isFinite(+b.lng))return json(res,400,{error:'Valid coordinates required'});r.lat=+b.lat;r.lng=+b.lng;r.lastLocationAt=new Date().toISOString();write(d);return json(res,200,{success:true})}
if(p==='/api/messages'&&req.method==='POST'){const b=await body(req);if(!String(b.message||'').trim())return json(res,400,{error:'Message required'});notify(d,'MESSAGE','Message for Admin',`${b.from||'User'}: ${String(b.message).trim()}`,b.sosId||null,b.responderId||null);write(d);return json(res,201,{success:true})}
if(p.startsWith('/api/road-blockages/')&&req.method==='DELETE'){const bid=p.split('/').pop(),i=d.roadBlockages.findIndex(x=>x.id===bid);if(i<0)return json(res,404,{error:'Blockage not found'});d.roadBlockages.splice(i,1);write(d);return json(res,200,{success:true})}
if(p==='/api/resources'&&req.method==='POST'){const b=await body(req);if(!b.type||!Number.isFinite(+b.qty)||+b.qty<=0)return json(res,400,{error:'Resource name and positive quantity are required.'});const x={id:'RES-'+Date.now().toString().slice(-7),type:b.type.trim(),qty:+b.qty,unit:b.unit||'units',supplier:b.supplier||'Local Relief Hub',lat:+b.lat||15.8281,lng:+b.lng||78.0373,capacity:Math.min(100,+b.capacity||50),createdAt:new Date().toISOString()};d.resources.unshift(x);audit(d,'RESOURCE_ADDED',x.id,{type:x.type,qty:x.qty});notify(d,'RESOURCE','New resource added',`${x.qty} ${x.unit} of ${x.type}`);write(d);return json(res,201,{success:true,resource:x})}
if(p==='/api/responder/login'&&req.method==='POST'){const b=await body(req),key=String(b.login||'').trim();const a=d.responderApplications.find(x=>x.phone===key||x.email===key);if(!a)return json(res,404,{error:'No application found. Please register first.'});if(a.passwordHash!==hash(b.password||''))return json(res,401,{error:'Invalid password'});if(a.status==='PENDING')return json(res,403,{error:'Application is still not approved',status:'PENDING'});if(a.status==='REJECTED')return json(res,403,{error:'Application was rejected',status:'REJECTED'});const r=d.responders.find(x=>x.phone===a.phone||x.email===a.email);if(!r)return json(res,409,{error:'Approved responder record unavailable'});if(!loginAllowed(req,'responder'))return json(res,429,{error:'Too many login attempts. Try again later.'});loginAttempts.delete(rateKey(req,'responder'));return json(res,200,{success:true,responderId:r.id,token:newSession('responder',r.id)})}
if(p.startsWith('/api/responders/')&&p.endsWith('/portal')&&req.method==='GET'){const id=p.split('/')[3];if(!requireResponder(req,res,id))return;const r=d.responders.find(x=>x.id===id);if(!r)return json(res,404,{error:'Responder not found'});const incidents=d.sos.filter(s=>(s.assignedResponders||[]).includes(id)&&s.status!=='RESOLVED');return json(res,200,{responder:{...r,passwordHash:undefined},incidents,notifications:r.notifications||[]})}
if(p.startsWith('/api/responders/')&&p.endsWith('/resource-request')&&req.method==='POST'){const id=p.split('/')[3];if(!requireResponder(req,res,id))return;const b=await body(req),r=d.responders.find(x=>x.id===id);if(!r)return json(res,404,{error:'Responder not found'});if(!b.message)return json(res,400,{error:'Resource message required'});notify(d,'RESOURCE_REQUEST','Responder resource update',`${r.name}: ${b.message}`,null,id);write(d);return json(res,201,{success:true})}
if(p==='/api/responder-applications'&&req.method==='POST'){
 const b=await body(req);if(!b.name||!b.phone||!b.location||!b.identityType||!b.identityProof||!b.password)return json(res,400,{error:'Basic details, organization/location and identity proof are required.'});const x={id:'APP-'+Date.now().toString().slice(-7),name:b.name,phone:b.phone,email:b.email||'',passwordHash:hash(b.password),organization:b.organization||'Independent Responder',skills:b.skills||[],location:b.location,lat:+b.lat||null,lng:+b.lng||null,identityType:b.identityType,identityProof:b.identityProof,submittedAt:new Date().toISOString(),status:'PENDING'};d.responderApplications.unshift(x);audit(d,'RESPONDER_APPLICATION_SUBMITTED',x.id,{name:x.name,organization:x.organization});notify(d,'APPLICATION','New responder application',`${x.name} submitted a responder/volunteer application`);write(d);return json(res,201,{success:true,application:{...x,identityProof:undefined}})}
if(p==='/api/responder-applications'&&req.method==='GET')return json(res,200,{applications:d.responderApplications});
if(p.startsWith('/api/responder-applications/')&&p.endsWith('/approve')&&req.method==='POST'){
 const id=p.split('/')[3],a=d.responderApplications.find(x=>x.id===id);if(!a)return json(res,404,{error:'Application not found'});if(a.status==='APPROVED')return json(res,409,{error:'Already approved'});a.status='APPROVED';const r={id:'RESP-'+Date.now().toString().slice(-7),name:a.name,organization:a.organization,status:'AVAILABLE',lat:a.lat||15.8281,lng:a.lng||78.0373,skills:a.skills||[],phone:a.phone,email:a.email||'',passwordHash:a.passwordHash,verified:true,assignments:[],notifications:[],identityType:a.identityType};d.responders.push(r);audit(d,'RESPONDER_APPLICATION_APPROVED',id,{responder:r.id});notify(d,'APPLICATION','Responder approved',`${a.name} is now available in the responder network`);write(d);return json(res,200,{success:true,responder:r})}
if(p.startsWith('/api/responder-applications/')&&p.endsWith('/reject')&&req.method==='POST'){const id=p.split('/')[3],a=d.responderApplications.find(x=>x.id===id);if(!a)return json(res,404,{error:'Application not found'});a.status='REJECTED';audit(d,'RESPONDER_APPLICATION_REJECTED',id);write(d);return json(res,200,{success:true})}
// Owner-only admin route. The normal /admin.html and /admin.js paths are deliberately unavailable.
if(p==='/admin.html'||p==='/admin.js')return json(res,404,{error:'Not found'});
if(p===ADMIN_PATH){
 if(!ownerAllowed(req))return json(res,403,{error:'Admin portal is restricted to the owner device'});
 const loginHtml=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RescuEZ — Owner Login</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07111d;color:#e8eef7;font-family:Arial,sans-serif}.card{width:min(420px,90vw);background:#0d1b2a;border:1px solid #29435e;border-radius:18px;padding:32px;box-sizing:border-box;box-shadow:0 20px 60px #0008}h1{margin:0 0 8px}p{color:#9eb1c7}.badge{color:#5ce0b2;font-size:12px;letter-spacing:2px;font-weight:bold}input{width:100%;box-sizing:border-box;margin:18px 0;padding:15px;border-radius:10px;border:1px solid #35516f;background:#07111d;color:#fff;font-size:16px}button{width:100%;padding:14px;border:0;border-radius:10px;background:#49b9db;color:#06131d;font-weight:bold;font-size:16px;cursor:pointer}.err{min-height:20px;color:#ff7388;margin-top:12px}</style></head><body><main class="card"><div class="badge">OWNER ONLY</div><h1>Admin Access</h1><p>Enter your admin password to open the Command Center.</p><form id="f"><input id="pw" type="password" autocomplete="current-password" placeholder="Admin password" required autofocus><button>Unlock Command Center</button><div class="err" id="e"></div></form></main><script>const f=document.getElementById('f'),e=document.getElementById('e'),pw=document.getElementById('pw');f.onsubmit=async ev=>{ev.preventDefault();e.textContent='';try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw.value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Login failed');sessionStorage.setItem('rescuez_admin_token',d.token);const page=await fetch('/api/admin/page',{headers:{Authorization:'Bearer '+d.token}});if(!page.ok){const x=await page.json().catch(()=>({}));throw Error(x.error||'Unable to open dashboard')}document.open();document.write(await page.text());document.close()}catch(x){e.textContent=x.message;pw.select()}};</script></body></html>`;
 res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});return res.end(loginHtml);
}
if(p==='/api/admin/page'&&req.method==='GET'){
 if(!ownerAllowed(req))return json(res,403,{error:'Admin portal is restricted to the owner device'});
 if(!requireAdmin(req,res))return;
 const fp=path.join(ROOT,'admin.html');let html=fs.readFileSync(fp,'utf8').replace('src="admin.js"','src="'+ADMIN_PATH+'/admin.js"');
 res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});return res.end(html);
}
if(p===ADMIN_PATH+'/admin.js'){
 if(!ownerAllowed(req))return json(res,403,{error:'Admin portal is restricted to the owner device'});
 const fp=path.join(ROOT,'admin.js');res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});return fs.createReadStream(fp).pipe(res);
}
let file=p==='/'?'index.html':p.slice(1),fp=path.normalize(path.join(ROOT,file));if(!fp.startsWith(ROOT))return json(res,403,{error:'forbidden'});if(fs.existsSync(fp)&&fs.statSync(fp).isFile()){
 if(file==='admin.html'){let html=fs.readFileSync(fp,'utf8').replace('src="admin.js"','src="'+ADMIN_PATH+'/admin.js"');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'});return res.end(html)}
 const ext=path.extname(fp),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin','Permissions-Policy':'geolocation=(self)','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});return fs.createReadStream(fp).pipe(res)}res.writeHead(404);res.end('Not found');
}catch(e){console.error(e);json(res,500,{error:'Server error'})}});server.listen(PORT,HOST,()=>console.log(`RescuEZ running at http://${HOST}:${PORT}`));
