let pickerMap, lastSOS=null; const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg,type='ok'){const t=$('toast');t.textContent=msg;t.className='toast '+type;clearTimeout(window.tt);window.tt=setTimeout(()=>t.className='',3200)}
function gps(){if(!navigator.geolocation)return toast('GPS is unavailable. Enter coordinates manually.','error');$('gpsmsg').textContent='Detecting your location…';navigator.geolocation.getCurrentPosition(p=>{$('lat').value=p.coords.latitude.toFixed(6);$('lng').value=p.coords.longitude.toFixed(6);$('gpsmsg').textContent='✓ Location detected. Ready to send.';toast('Location captured.');if(pickerMap)pickerMap.setView([p.coords.latitude,p.coords.longitude],15)},()=>{$('gpsmsg').textContent='Location permission unavailable. You can enter coordinates or pick on map.';toast('Location permission denied.','error')},{enableHighAccuracy:true,timeout:10000})}
function openMapPicker(){const p=$('picker');p.classList.remove('hidden');setTimeout(()=>{if(pickerMap)pickerMap.remove();pickerMap=L.map('pickMap').setView([+$('lat').value||15.8281,+$('lng').value||78.0373],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(pickerMap);pickerMap.on('click',e=>{$('lat').value=e.latlng.lat.toFixed(6);$('lng').value=e.latlng.lng.toFixed(6);$('gpsmsg').textContent='✓ Map location selected.';L.marker(e.latlng).addTo(pickerMap)});pickerMap.invalidateSize()},50)}
$('sosForm').addEventListener('submit',async e=>{e.preventDefault();const b={name:$('name').value.trim(),phone:$('phone').value.trim(),category:$('category').value,people:+$('people').value||1,severityScore:+$('severity').value,needs:$('needs').value.trim(),description:$('desc').value.trim(),lat:+$('lat').value,lng:+$('lng').value,medical:$('category').value==='Medical',trapped:$('category').value==='Trapped Person'};if(!b.name||!Number.isFinite(b.lat)||!Number.isFinite(b.lng)||b.lat<-90||b.lat>90||b.lng<-180||b.lng>180)return toast('Please enter your name and valid location.','error');const btn=e.submitter;btn.disabled=true;btn.innerHTML='<span class="spinner"></span> Sending securely…';try{const r=await fetch('/api/sos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();if(!r.ok)throw Error(d.error);lastSOS=d.sos;showConfirmation(d.sos)}catch(err){toast(err.message||'Unable to send SOS.','error');btn.disabled=false;btn.textContent='🚨 CONFIRM & SEND SOS'}});
function showConfirmation(x){$('sosForm').classList.add('hidden');const c=$('myRequest');c.classList.remove('hidden');c.innerHTML=`<div class="success-orb">✓</div><div class="eyebrow">SOS RECEIVED</div><h2>Your request is now in the response network.</h2><p class="muted">Reference this ID when contacting the response team.</p><div class="request-grid"><div><small>REFERENCE</small><b>${esc(x.id)}</b></div><div><small>PRIORITY</small><b class="${x.priority}">${x.priority} · ${x.priorityScore}/100</b></div><div><small>CURRENT STATUS</small><b id="userStatus">${esc(x.status)}</b></div><div><small>LOCATION</small><b>${Number(x.lat).toFixed(6)}, ${Number(x.lng).toFixed(6)}</b></div></div><div id="statusTimeline" class="status-timeline"></div><div id="userEta" class="notice">Waiting for command center assignment…</div><button class="primary" onclick="location.reload()">Submit another request</button>`;window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});pollStatus(x.id)}
async function pollStatus(id){try{const r=await fetch('/api/sos/'+encodeURIComponent(id)),d=await r.json();if(r.ok&&d.sos){const x=d.sos;if($('userStatus'))$('userStatus').textContent=x.status+(x.route?` · ETA ${x.route.etaMin} min`:'');if($('userEta'))$('userEta').textContent=x.status==='NEW'?'SOS received. Command center is reviewing your request.':x.status==='EN_ROUTE'?`Help is on the way. Estimated arrival: ${x.route?.etaMin??'calculating'} min.`:x.status==='RESOLVED'?'Your incident has been marked resolved.':`Your request status is ${x.status}.`;if($('statusTimeline'))$('statusTimeline').innerHTML=(x.statusHistory||[]).map(h=>`<div class="status-step"><i></i><div><b>${esc(h.status.replaceAll('_',' '))}</b><span>${esc(h.note||'')}</span><small>${new Date(h.at).toLocaleString()}</small></div></div>`).join('')}}catch{}setTimeout(()=>pollStatus(id),4000)}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
let joinPickerMap, joinMarker;
function openResponderLogin(){window.location.href='responder.html'}
function openJoinMapPicker(){
 const box=$('joinPicker'); box.classList.remove('hidden');
 setTimeout(()=>{try{
  if(joinPickerMap)joinPickerMap.remove();
  const lat=+$('joinLat').value||+$('lat').value||15.8281, lng=+$('joinLng').value||+$('lng').value||78.0373;
  joinPickerMap=L.map('joinPickMap').setView([lat,lng],13);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(joinPickerMap);
  const setPos=e=>{const q=e.latlng||e;$('joinLat').value=q.lat.toFixed(6);$('joinLng').value=q.lng.toFixed(6);if(joinMarker)joinMarker.setLatLng(q);else joinMarker=L.marker(q).addTo(joinPickerMap);$('joinMapMsg').textContent='✓ Responder location selected.'};
  joinPickerMap.on('click',setPos); joinPickerMap.invalidateSize();
 }catch(e){toast('Map could not be opened. Please enter coordinates manually.','error')}},80)
}
function useJoinCurrentLocation(){if(!navigator.geolocation)return toast('GPS unavailable.','error');navigator.geolocation.getCurrentPosition(p=>{const q={lat:p.coords.latitude,lng:p.coords.longitude};$('joinLat').value=q.lat.toFixed(6);$('joinLng').value=q.lng.toFixed(6);$('joinMapMsg').textContent='✓ Current location selected.';if(joinPickerMap){joinPickerMap.setView([q.lat,q.lng],15);if(joinMarker)joinMarker.setLatLng(q);else joinMarker=L.marker(q).addTo(joinPickerMap)}},()=>toast('Location permission denied.','error'),{enableHighAccuracy:true,timeout:10000})}
function sendVictimMessage(){const m=$('askAdminVictim')?.value.trim();if(!m)return;fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:'Victim',message:m})}).then(r=>r.json()).then(()=>{ $('askAdminVictim').value='';toast('Message sent to Admin.')}).catch(e=>toast(e.message,'error'))}
function openResponderJoin(){$('modalRoot').innerHTML=`<div class="modal"><div class="modalbox large"><div class="modal-head"><div><div class="eyebrow">RESPONDER ONBOARDING</div><h2>Join RescuEZ</h2></div><button class="ghost" onclick="closeJoin()">✕</button></div><form id="joinForm" class="formgrid"><div class="field"><label>Full name *</label><input id="joinName" required></div><div class="field"><label>Phone *</label><input id="joinPhone" required></div><div class="field"><label>Email (optional)</label><input id="joinEmail" type="email"></div><div class="field"><label>Password *</label><input id="joinPassword" type="password" minlength="6" required></div><div class="field"><label>Team / organization *</label><input id="joinOrg" required></div><div class="field"><label>Skills</label><input id="joinSkills" placeholder="Medical, Rescue, Driving"></div><div class="field full"><label>Organization / individual location *</label><input id="joinLocation" required placeholder="Area, city, district"></div><div class="field full"><div class="location-actions"><button type="button" class="ghost" onclick="openJoinMapPicker()">⌖ Pick location on map</button><button type="button" class="primary" onclick="useJoinCurrentLocation()">⌖ Use current location</button></div><div id="joinPicker" class="picker hidden"><div id="joinPickMap"></div><small>Click anywhere on the map to select responder location.</small></div><div id="joinMapMsg" class="muted"></div></div><div class="field"><label>Latitude</label><input id="joinLat" placeholder="15.8281"></div><div class="field"><label>Longitude</label><input id="joinLng" placeholder="78.0373"></div><div class="field"><label>Identity proof type *</label><select id="identityType"><option>Aadhaar</option><option>Voter ID</option><option>PAN</option><option>Passport</option></select></div><div class="field"><label>Identity proof *</label><input id="identityFile" type="file" accept="image/*,.pdf" required></div><div class="field full"><div class="notice warning">Your identity proof is sent for admin verification. This is a local prototype; production must use private encrypted storage.</div></div><div class="field full"><button class="primary" type="submit">Submit application</button></div></form></div></div>`;$('joinForm').onsubmit=submitResponderApplication}
async function submitResponderApplication(e){e.preventDefault();try{const f=$('identityFile').files[0];if(!f)return;const proof=await fileData(f);const r=await fetch('/api/responder-applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('joinName').value.trim(),phone:$('joinPhone').value.trim(),email:$('joinEmail').value.trim(),password:$('joinPassword').value,organization:$('joinOrg').value.trim(),skills:$('joinSkills').value.split(',').map(x=>x.trim()).filter(Boolean),location:$('joinLocation').value.trim(),lat:+$('joinLat').value||null,lng:+$('joinLng').value||null,identityType:$('identityType').value,identityProof:proof})});const d=await r.json();if(!r.ok)throw Error(d.error);closeJoin();toast('Application submitted. Admin verification is pending.')}catch(e){toast(e.message,'error')}}
function closeJoin(){$('modalRoot').innerHTML=''}
